# Run the database in a container and then run app.py locally.
# Todo: add another container for app.py 
version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpasswordhere
