name: Docker deployment check

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 8 * * 0" 

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build